name: shelf_book_tracker
description: A warm, editorial reading journal UI prototype.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: book-stack.png
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FAF6D7"
  web:
    generate: true
    image_path: book-stack.png
    background_color: "#FAF6D7"
    theme_color: "#F2A21A"
  windows:
    generate: true
    image_path: book-stack.png
    icon_size: 48
